### ISSUE TITLE
Send email on Streamlit app

### ISSUE THREAD

**Issue by JohnTan38** [tonykipkemboi/streamlit-smtp-test#1]
Dear Sir

Thank you for the excellent code.
Is there a config file (or equivalent) where we can save login id and password?
Please share how to use st.secrets(). Thank you very much!

**Comment by tonykipkemboi** [comment]
Hi @JohnTan38,

I am glad you found the code helpful. Can you describe the flow of the app you're building and how it will use the config file? Could you give me more info so I can give you a better answer? For secrets, we have [this page](https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management), which is an excellent guide for using secrets.

**Comment by JohnTan38** [comment]
Hello sir. We've figured out a solution. Thank you once again for this excellent app!

**Comment by tonykipkemboi** [comment]
Glad it worked!
